import React from "react";
import Head from "next/head";
import { BsSun, BsMoonStars } from "react-icons/bs";

const Layout = ({ children }: { children: React.ReactNode }) => {
  const [theme, setTheme] = React.useState("black");

  React.useEffect(() => {
    const body = document.documentElement;
    body.setAttribute("data-theme", theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme(theme === "lofi" ? "black" : "lofi");
  };

  return (
    <div
      className="h-full w-screen flex flex-col items-center px-2 py-5"
      // data-theme={theme}
    >
      <Head>
        <title>Justin Frazier Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col justify-between w-full max-w-5xl h-screen">
        <nav className="flex justify-between w-full">
          <p>JF.</p>
          <button
            onClick={toggleTheme}
            className="btn btn-sm btn-ghost w-11 h-10 border border-current rounded"
          >
            {theme === "lofi" ? <BsMoonStars size={20} /> : <BsSun size={25} />}
          </button>
        </nav>
        <main className="w-full">{children}</main>
        <footer className="flex justify-center w-full">Footer</footer>
      </div>
    </div>
  );
};

export default Layout;
